# ============================================
# CONFIGURACIÓN PRINCIPAL - BOT QUANT INSTITUCIONAL
# ============================================

SIMULATION_MODE = True
EXCHANGE_NAME = "okx"

CAPITAL_INICIAL = 1000
MAX_POSICIONES = 4
MAX_CAPITAL_USO = 0.60

TIMEFRAME = "5m"
CYCLE_SECONDS = 10
HISTORY_LIMIT = 200

UNIVERSE = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "ADA/USDT", "DOGE/USDT",
    "LINK/USDT", "DOT/USDT", "AAVE/USDT", "UNI/USDT", "MATIC/USDT"
]
MIN_AVG_VOLUME_USD = 10_000_000

ML_RETRAIN_EVERY_TRADES = 30
ML_MIN_TRADES_FOR_TRAIN = 30
ML_FEATURES_WINDOW = 50

DEFAULT_ATR_PERIOD = 14
DEFAULT_STOP_MULTIPLIER = 1.5
DEFAULT_TAKE_MULTIPLIER = 2.5
MAX_STOP_PERCENT = 0.05
MIN_STOP_PERCENT = 0.005

KELLY_FRACTION = 0.25
MAX_POSITION_SIZE_PCT = 0.15
MIN_POSITION_SIZE_PCT = 0.03

COOLDOWN_BASE = 10
COOLDOWN_MAX = 60
COOLDOWN_MIN = 5

SIGNAL_MIN_PROBABILITY = 0.60
SIGNAL_MIN_SCORE = 0.65

CORRELATION_GROUPS = {
    "L1": ["BTC/USDT", "ETH/USDT"],
    "L2": ["SOL/USDT"],
    "L3": ["ADA/USDT"],
    "MEME": ["DOGE/USDT"],
    "L4": ["LINK/USDT"],
    "L5": ["DOT/USDT"],
    "L6": ["AAVE/USDT", "UNI/USDT"],
    "L7": ["MATIC/USDT"],
}

MODEL_PATH = "xgboost_model.pkl"
SCALER_PATH = "scaler.pkl"
TRADES_LOG = "trades.csv"
PORTFOLIO_STATE = "portfolio_state.json"

OKX_API_KEY = "TU_API_KEY"
OKX_SECRET_KEY = "TU_SECRET"
OKX_PASSPHRASE = "TU_PASSPHRASE"
BINANCE_API_KEY = "TU_API_KEY"
BINANCE_SECRET_KEY = "TU_SECRET"
