# ============================================
# CONFIGURACIÓN INSTITUCIONAL - 12 ACTIVOS (CICLO 45s)
# UMBRALES RELAJADOS PARA ENTRENAMIENTO INICIAL
# Se reemplazaron UNI, MATIC y SUI por XRP, LTC y HBAR
# ============================================

SIMULATION_MODE = True
DATA_SOURCE = "yfinance"

CAPITAL_INICIAL = 1000
MAX_POSICIONES = 4
MAX_CAPITAL_USO = 0.60

TIMEFRAME = "5m"
CYCLE_SECONDS = 45
HISTORY_LIMIT = 100

# Universo actualizado (12 activos, todos con datos en Yahoo Finance)
UNIVERSE = [
    "BTC-USD", "ETH-USD", "SOL-USD", "AVAX-USD", "ADA-USD", "NEAR-USD",
    "LINK-USD", "DOT-USD", "DOGE-USD", "XRP-USD", "LTC-USD", "HBAR-USD"
]
SYMBOL_MAP = {
    "BTC-USD": "BTC/USDT", "ETH-USD": "ETH/USDT", "SOL-USD": "SOL/USDT",
    "AVAX-USD": "AVAX/USDT", "ADA-USD": "ADA/USDT", "NEAR-USD": "NEAR/USDT",
    "LINK-USD": "LINK/USDT", "DOT-USD": "DOT/USDT", "DOGE-USD": "DOGE/USDT",
    "XRP-USD": "XRP/USDT", "LTC-USD": "LTC/USDT", "HBAR-USD": "HBAR/USDT"
}

ADX_PERIOD = 14
TREND_STRENGTH_THRESHOLD = 25

ML_RETRAIN_EVERY_TRADES = 30
ML_MIN_TRADES_FOR_TRAIN = 30

# ========== RIESGO/RECOMPENSA ==========
DEFAULT_ATR_PERIOD = 14
DEFAULT_STOP_MULTIPLIER = 1.0        # Stop loss = 1.0 × ATR
DEFAULT_TAKE_MULTIPLIER = 10.0       # Take profit = 10.0 × ATR
MAX_STOP_PERCENT = 0.02
MIN_STOP_PERCENT = 0.005

TRAILING_ACTIVATION = 0.01
TRAILING_GAP = 0.005

KELLY_FRACTION = 0.25
MAX_POSITION_SIZE_PCT = 0.16
MIN_POSITION_SIZE_PCT = 0.08

COOLDOWN_BASE = 20
COOLDOWN_MAX = 60
COOLDOWN_MIN = 10

# Grupos de correlación actualizados
CORRELATION_GROUPS = {
    "L1": ["BTC-USD", "ETH-USD", "XRP-USD", "LTC-USD"],
    "L2": ["SOL-USD", "AVAX-USD"],
    "L3": ["ADA-USD", "NEAR-USD", "HBAR-USD"],
    "DEFI": ["LINK-USD"],
    "L4": ["DOT-USD"],
    "MEME": ["DOGE-USD"],
}

# UMBRALES RELAJADOS PARA PERMITIR TRADES MIENTRAS SE ENTREENA EL ML
SIGNAL_MIN_PROBABILITY = 0.50   # Antes 0.55
SIGNAL_MIN_SCORE = 0.50         # Antes 0.60

MODEL_PATH = "xgboost_model.pkl"
SCALER_PATH = "scaler.pkl"
TRADES_LOG = "trades.csv"
PORTFOLIO_STATE = "portfolio_state.json"