SIMULATION_MODE = True
EXCHANGE_NAME = "bybit"

CAPITAL_INICIAL = 1000
MAX_POSICIONES = 4
MAX_CAPITAL_USO = 0.60

TIMEFRAME = "5m"
CYCLE_SECONDS = 10
HISTORY_LIMIT = 200

UNIVERSE = [
    "BTC/USDT", "ETH/USDT", "SOL/USDT", "ADA/USDT", "DOGE/USDT",
    "LINK/USDT", "DOT/USDT", "AAVE/USDT", "UNI/USDT", "MATIC/USDT"
]
MIN_AVG_VOLUME_USD = 10_000_000

DEFAULT_ATR_PERIOD = 14
DEFAULT_STOP_MULTIPLIER = 1.2
DEFAULT_TAKE_MULTIPLIER = 2.5
MAX_STOP_PERCENT = 0.03
MIN_STOP_PERCENT = 0.005

KELLY_FRACTION = 0.15
MAX_POSITION_SIZE_PCT = 0.08
MIN_POSITION_SIZE_PCT = 0.02

COOLDOWN_BASE = 30
COOLDOWN_MAX = 90
COOLDOWN_MIN = 10

SIGNAL_MIN_RSI = 30
SIGNAL_MAX_RSI = 70
SIGNAL_MIN_TREND_SCORE = 0.5

CORRELATION_GROUPS = {
    "L1": ["BTC/USDT", "ETH/USDT"],
    "L2": ["SOL/USDT"],
    "L3": ["ADA/USDT"],
    "MEME": ["DOGE/USDT"],
    "L4": ["LINK/USDT"],
    "L5": ["DOT/USDT"],
    "L6": ["AAVE/USDT", "UNI/USDT"],
    "L7": ["MATIC/USDT"],
}

MODEL_PATH = "model.pkl"
SCALER_PATH = "scaler.pkl"
TRADES_LOG = "trades.csv"
PORTFOLIO_STATE = "portfolio_state.json"

BYBIT_API_KEY = ""
BYBIT_SECRET_KEY = ""